// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confio/twasm/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	github_com_CosmWasm_wasmd_x_wasm_types "github.com/CosmWasm/wasmd/x/wasm/types"
	types "github.com/CosmWasm/wasmd/x/wasm/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

var (
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	// Params sdk type Params for wasmd
	Params types.Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// Codes has all stored wasm codes and metadata
	Codes []types.Code `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes,omitempty"`
	// Contracts contains all instantiated contracts, state and metadata
	Contracts []Contract `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts,omitempty"`
	// Sequences names and values
	Sequences []types.Sequence `protobuf:"bytes,4,rep,name=sequences,proto3" json:"sequences,omitempty"`
	// PrivilegedContractAddresses is a list of contract addresses that can have
	// special permissions
	PrivilegedContractAddresses []string `protobuf:"bytes,6,rep,name=privileged_contract_addresses,json=privilegedContractAddresses,proto3" json:"privileged_contract_addresses,omitempty"`
	// PinnedCodeIDs has codeInfo ids for wasm codes that are pinned in cache
	PinnedCodeIDs []uint64 `protobuf:"varint,7,rep,packed,name=pinned_code_ids,json=pinnedCodeIds,proto3" json:"pinned_code_ids,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4cd47eb0533ed, []int{0}
}

func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}

func (m *GenesisState) XXX_Size() int {
	return m.Size()
}

func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() types.Params {
	if m != nil {
		return m.Params
	}
	return types.Params{}
}

func (m *GenesisState) GetCodes() []types.Code {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *GenesisState) GetContracts() []Contract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *GenesisState) GetSequences() []types.Sequence {
	if m != nil {
		return m.Sequences
	}
	return nil
}

func (m *GenesisState) GetPrivilegedContractAddresses() []string {
	if m != nil {
		return m.PrivilegedContractAddresses
	}
	return nil
}

func (m *GenesisState) GetPinnedCodeIDs() []uint64 {
	if m != nil {
		return m.PinnedCodeIDs
	}
	return nil
}

// Contract struct encompasses ContractAddress, ContractInfo, and ContractState
type Contract struct {
	ContractAddress string             `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ContractInfo    types.ContractInfo `protobuf:"bytes,2,opt,name=contract_info,json=contractInfo,proto3" json:"contract_info"`
	// ContractSate is one of default wasmd Model or custom state model
	//
	// Types that are valid to be assigned to ContractState:
	//	*Contract_KvModel
	//	*Contract_CustomModel
	ContractState       isContract_ContractState         `protobuf_oneof:"contract_state"`
	ContractCodeHistory []types.ContractCodeHistoryEntry `protobuf:"bytes,5,rep,name=contract_code_history,json=contractCodeHistory,proto3" json:"contract_code_history"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4cd47eb0533ed, []int{1}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}

func (m *Contract) XXX_Size() int {
	return m.Size()
}

func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

type isContract_ContractState interface {
	isContract_ContractState()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Contract_KvModel struct {
	KvModel *KVModel `protobuf:"bytes,3,opt,name=kv_model,json=kvModel,proto3,oneof" json:"kv_model,omitempty"`
}
type Contract_CustomModel struct {
	CustomModel *CustomModel `protobuf:"bytes,4,opt,name=custom_model,json=customModel,proto3,oneof" json:"custom_model,omitempty"`
}

func (*Contract_KvModel) isContract_ContractState()     {}
func (*Contract_CustomModel) isContract_ContractState() {}

func (m *Contract) GetContractState() isContract_ContractState {
	if m != nil {
		return m.ContractState
	}
	return nil
}

func (m *Contract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Contract) GetContractInfo() types.ContractInfo {
	if m != nil {
		return m.ContractInfo
	}
	return types.ContractInfo{}
}

func (m *Contract) GetKvModel() *KVModel {
	if x, ok := m.GetContractState().(*Contract_KvModel); ok {
		return x.KvModel
	}
	return nil
}

func (m *Contract) GetCustomModel() *CustomModel {
	if x, ok := m.GetContractState().(*Contract_CustomModel); ok {
		return x.CustomModel
	}
	return nil
}

func (m *Contract) GetContractCodeHistory() []types.ContractCodeHistoryEntry {
	if m != nil {
		return m.ContractCodeHistory
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Contract) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Contract_KvModel)(nil),
		(*Contract_CustomModel)(nil),
	}
}

// KVModel is a wrapper around the wasmd default key value model.
type KVModel struct {
	Models []types.Model `protobuf:"bytes,1,rep,name=models,proto3" json:"models"`
}

func (m *KVModel) Reset()         { *m = KVModel{} }
func (m *KVModel) String() string { return proto.CompactTextString(m) }
func (*KVModel) ProtoMessage()    {}
func (*KVModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4cd47eb0533ed, []int{2}
}

func (m *KVModel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *KVModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVModel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *KVModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVModel.Merge(m, src)
}

func (m *KVModel) XXX_Size() int {
	return m.Size()
}

func (m *KVModel) XXX_DiscardUnknown() {
	xxx_messageInfo_KVModel.DiscardUnknown(m)
}

var xxx_messageInfo_KVModel proto.InternalMessageInfo

func (m *KVModel) GetModels() []types.Model {
	if m != nil {
		return m.Models
	}
	return nil
}

// CustomModel contains the raw json data for a contract to seed its state on
// import
type CustomModel struct {
	// Msg json encoded message to be passed to the contract on import
	Msg github_com_CosmWasm_wasmd_x_wasm_types.RawContractMessage `protobuf:"bytes,5,opt,name=msg,proto3,casttype=github.com/CosmWasm/wasmd/x/wasm/types.RawContractMessage" json:"msg,omitempty"`
}

func (m *CustomModel) Reset()         { *m = CustomModel{} }
func (m *CustomModel) String() string { return proto.CompactTextString(m) }
func (*CustomModel) ProtoMessage()    {}
func (*CustomModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4cd47eb0533ed, []int{3}
}

func (m *CustomModel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *CustomModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustomModel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *CustomModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomModel.Merge(m, src)
}

func (m *CustomModel) XXX_Size() int {
	return m.Size()
}

func (m *CustomModel) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomModel.DiscardUnknown(m)
}

var xxx_messageInfo_CustomModel proto.InternalMessageInfo

func (m *CustomModel) GetMsg() github_com_CosmWasm_wasmd_x_wasm_types.RawContractMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "confio.twasm.v1beta1.GenesisState")
	proto.RegisterType((*Contract)(nil), "confio.twasm.v1beta1.Contract")
	proto.RegisterType((*KVModel)(nil), "confio.twasm.v1beta1.KVModel")
	proto.RegisterType((*CustomModel)(nil), "confio.twasm.v1beta1.CustomModel")
}

func init() {
	proto.RegisterFile("confio/twasm/v1beta1/genesis.proto", fileDescriptor_89c4cd47eb0533ed)
}

var fileDescriptor_89c4cd47eb0533ed = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5d, 0x4f, 0xd4, 0x4e,
	0x14, 0xc6, 0x77, 0xd9, 0x17, 0xd8, 0xd9, 0xe5, 0x0f, 0x99, 0x3f, 0x4a, 0x59, 0xa4, 0xbb, 0xee,
	0x85, 0xae, 0x2f, 0x69, 0x03, 0x46, 0x13, 0x4d, 0x4c, 0xb0, 0x88, 0x82, 0x86, 0x48, 0x96, 0x88,
	0xd1, 0x0b, 0x37, 0xdd, 0xce, 0x50, 0x1a, 0x68, 0xa7, 0xf6, 0x0c, 0x0b, 0xfb, 0x25, 0x8c, 0x1f,
	0x8b, 0x4b, 0x2e, 0xbd, 0x6a, 0xcc, 0x72, 0xc7, 0x47, 0x30, 0x5e, 0x98, 0x4e, 0xa7, 0xdd, 0xc2,
	0x82, 0x77, 0x6d, 0xcf, 0xef, 0x3c, 0xcf, 0x3c, 0x93, 0xd3, 0x83, 0x5a, 0x16, 0xf3, 0xf6, 0x1c,
	0xa6, 0xf3, 0x63, 0x13, 0x5c, 0xbd, 0xbf, 0xdc, 0xa3, 0xdc, 0x5c, 0xd6, 0x6d, 0xea, 0x51, 0x70,
	0x40, 0xf3, 0x03, 0xc6, 0x19, 0x9e, 0x8b, 0x19, 0x4d, 0x30, 0x9a, 0x64, 0xea, 0x73, 0x36, 0xb3,
	0x99, 0x00, 0xf4, 0xe8, 0x29, 0x66, 0xeb, 0xaa, 0xc5, 0xc0, 0x65, 0xa0, 0xf7, 0x4c, 0xa0, 0xa9,
	0x9c, 0xc5, 0x1c, 0x2f, 0x5b, 0x17, 0x5e, 0xd2, 0xf0, 0xb2, 0x57, 0xfd, 0xce, 0x58, 0x9d, 0x0f,
	0x7c, 0x9a, 0x54, 0x17, 0xc6, 0xab, 0x27, 0x71, 0xa9, 0xf5, 0xbd, 0x88, 0x6a, 0x6f, 0x63, 0xa9,
	0x1d, 0x6e, 0x72, 0x8a, 0x9f, 0xa1, 0xb2, 0x6f, 0x06, 0xa6, 0x0b, 0x4a, 0xbe, 0x99, 0x6f, 0x57,
	0x57, 0x14, 0x2d, 0x69, 0xd6, 0x64, 0x0e, 0x6d, 0x5b, 0xd4, 0x8d, 0xe2, 0x69, 0xd8, 0xc8, 0x75,
	0x24, 0x8d, 0xd7, 0x51, 0xc9, 0x62, 0x84, 0x82, 0x32, 0xd1, 0x2c, 0xb4, 0xab, 0x2b, 0xb7, 0xc7,
	0xdb, 0xd6, 0x18, 0xa1, 0xc6, 0x7c, 0xd4, 0x74, 0x11, 0x36, 0x66, 0x04, 0xfc, 0x98, 0xb9, 0x0e,
	0xa7, 0xae, 0xcf, 0x07, 0x9d, 0xb8, 0x1b, 0x7f, 0x46, 0x15, 0x8b, 0x79, 0x3c, 0x30, 0x2d, 0x0e,
	0x4a, 0x41, 0x48, 0xa9, 0xda, 0x75, 0x17, 0xa9, 0xad, 0x49, 0xcc, 0x58, 0x94, 0x92, 0xff, 0xa7,
	0x8d, 0x19, 0xd9, 0x91, 0x1a, 0xfe, 0x88, 0x2a, 0x40, 0xbf, 0x1d, 0x51, 0xcf, 0xa2, 0xa0, 0x14,
	0x85, 0x74, 0x7d, 0xfc, 0x94, 0x3b, 0x12, 0x19, 0xc9, 0xa6, 0x4d, 0x59, 0xd9, 0xf4, 0x23, 0x66,
	0x68, 0xc9, 0x0f, 0x9c, 0xbe, 0x73, 0x48, 0x6d, 0x4a, 0xba, 0x89, 0x5d, 0xd7, 0x24, 0x24, 0xa0,
	0x00, 0x14, 0x94, 0x72, 0xb3, 0xd0, 0xae, 0x18, 0x8f, 0x2e, 0xc2, 0xc6, 0xfd, 0x7f, 0x82, 0x19,
	0xf9, 0xc5, 0x11, 0x98, 0xc4, 0x7c, 0x95, 0x60, 0x78, 0x17, 0xcd, 0xf8, 0x8e, 0xe7, 0x09, 0x0d,
	0x42, 0xbb, 0x0e, 0x01, 0x65, 0xb2, 0x59, 0x68, 0x17, 0x0d, 0x6d, 0x18, 0x36, 0xa6, 0xb7, 0x45,
	0x29, 0xba, 0xeb, 0xcd, 0xd7, 0x70, 0x11, 0x36, 0x16, 0xae, 0xb0, 0x19, 0x97, 0x69, 0x7f, 0xc4,
	0x12, 0x78, 0x57, 0x9c, 0x2a, 0xcd, 0x96, 0x5b, 0x7f, 0x26, 0xd0, 0x54, 0xe2, 0x89, 0x1f, 0xa0,
	0xd9, 0xab, 0xe7, 0x14, 0x63, 0x51, 0xe9, 0xcc, 0x58, 0x97, 0xcf, 0x85, 0x37, 0xd1, 0x74, 0x8a,
	0x3a, 0xde, 0x1e, 0x53, 0x26, 0xc4, 0xf8, 0xa8, 0xd7, 0xcd, 0x41, 0x8c, 0x6d, 0x7a, 0x7b, 0x4c,
	0x0e, 0x51, 0xcd, 0xca, 0x7c, 0xc3, 0x2f, 0xd0, 0xd4, 0x41, 0xbf, 0xeb, 0x32, 0x42, 0x0f, 0x95,
	0x82, 0x50, 0x59, 0xba, 0x7e, 0x04, 0xde, 0xef, 0x6e, 0x45, 0xd0, 0x46, 0xae, 0x33, 0x79, 0xd0,
	0x17, 0x8f, 0xf8, 0x0d, 0xaa, 0x59, 0x47, 0xc0, 0x99, 0x2b, 0xfb, 0x8b, 0xa2, 0xff, 0xee, 0x0d,
	0x23, 0x24, 0xc8, 0x44, 0xa3, 0x6a, 0x8d, 0x5e, 0x31, 0x41, 0xb7, 0xd2, 0x38, 0xe2, 0xea, 0xf6,
	0x1d, 0xe0, 0x2c, 0x18, 0x28, 0x25, 0x31, 0x38, 0x0f, 0x6f, 0x8e, 0x15, 0x5d, 0xe7, 0x46, 0x0c,
	0xaf, 0x7b, 0x3c, 0x18, 0xc8, 0x88, 0xe9, 0x74, 0x66, 0xea, 0xc6, 0x2c, 0xfa, 0x2f, 0x75, 0x81,
	0xe8, 0xf7, 0x6b, 0xad, 0xa2, 0x49, 0x99, 0x0a, 0x3f, 0x45, 0x65, 0x91, 0x21, 0xba, 0xf2, 0xc8,
	0x73, 0x7e, 0xdc, 0x53, 0x80, 0xc9, 0x8f, 0x18, 0xc3, 0xad, 0xaf, 0xa8, 0x9a, 0xc9, 0x85, 0x3f,
	0xa0, 0x82, 0x0b, 0xb6, 0x52, 0x6a, 0xe6, 0xdb, 0x35, 0xe3, 0xe5, 0xef, 0xb0, 0xf1, 0xdc, 0x76,
	0xf8, 0xfe, 0x51, 0x4f, 0xb3, 0x98, 0xab, 0xaf, 0x31, 0x70, 0x3f, 0x25, 0x7b, 0x81, 0xe8, 0x27,
	0xf1, 0x7e, 0x88, 0x57, 0x47, 0xc7, 0x3c, 0x4e, 0x22, 0x6d, 0x51, 0x00, 0xd3, 0xa6, 0x9d, 0x48,
	0xc9, 0x58, 0x3d, 0x1d, 0xaa, 0xf9, 0xb3, 0xa1, 0x9a, 0xff, 0x35, 0x54, 0xf3, 0x3f, 0xce, 0xd5,
	0xdc, 0xd9, 0xb9, 0x9a, 0xfb, 0x79, 0xae, 0xe6, 0xbe, 0xdc, 0xcb, 0x28, 0x27, 0xfb, 0xd1, 0x0e,
	0x4c, 0x42, 0xf5, 0x13, 0xb9, 0x28, 0x85, 0x72, 0xaf, 0x2c, 0x56, 0xcf, 0x93, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0x96, 0x5c, 0x41, 0x45, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PinnedCodeIDs) > 0 {
		dAtA2 := make([]byte, len(m.PinnedCodeIDs)*10)
		var j1 int
		for _, num := range m.PinnedCodeIDs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGenesis(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PrivilegedContractAddresses) > 0 {
		for iNdEx := len(m.PrivilegedContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PrivilegedContractAddresses[iNdEx])
			copy(dAtA[i:], m.PrivilegedContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.PrivilegedContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Sequences) > 0 {
		for iNdEx := len(m.Sequences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contracts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Codes) > 0 {
		for iNdEx := len(m.Codes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Codes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractCodeHistory) > 0 {
		for iNdEx := len(m.ContractCodeHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractCodeHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ContractState != nil {
		{
			size := m.ContractState.Size()
			i -= size
			if _, err := m.ContractState.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	{
		size, err := m.ContractInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Contract_KvModel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract_KvModel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.KvModel != nil {
		{
			size, err := m.KvModel.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func (m *Contract_CustomModel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract_CustomModel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomModel != nil {
		{
			size, err := m.CustomModel.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *KVModel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVModel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVModel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Models) > 0 {
		for iNdEx := len(m.Models) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Models[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CustomModel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustomModel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomModel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Codes) > 0 {
		for _, e := range m.Codes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Contracts) > 0 {
		for _, e := range m.Contracts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Sequences) > 0 {
		for _, e := range m.Sequences {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PrivilegedContractAddresses) > 0 {
		for _, s := range m.PrivilegedContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PinnedCodeIDs) > 0 {
		l = 0
		for _, e := range m.PinnedCodeIDs {
			l += sovGenesis(uint64(e))
		}
		n += 1 + sovGenesis(uint64(l)) + l
	}
	return n
}

func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.ContractInfo.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.ContractState != nil {
		n += m.ContractState.Size()
	}
	if len(m.ContractCodeHistory) > 0 {
		for _, e := range m.ContractCodeHistory {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Contract_KvModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KvModel != nil {
		l = m.KvModel.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Contract_CustomModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomModel != nil {
		l = m.CustomModel.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *KVModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Models) > 0 {
		for _, e := range m.Models {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *CustomModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Codes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Codes = append(m.Codes, types.Code{})
			if err := m.Codes[len(m.Codes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, Contract{})
			if err := m.Contracts[len(m.Contracts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequences = append(m.Sequences, types.Sequence{})
			if err := m.Sequences[len(m.Sequences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivilegedContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivilegedContractAddresses = append(m.PrivilegedContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.PinnedCodeIDs = append(m.PinnedCodeIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGenesis
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGenesis
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.PinnedCodeIDs) == 0 {
					m.PinnedCodeIDs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.PinnedCodeIDs = append(m.PinnedCodeIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field PinnedCodeIDs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ContractInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvModel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KVModel{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ContractState = &Contract_KvModel{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomModel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CustomModel{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ContractState = &Contract_CustomModel{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractCodeHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractCodeHistory = append(m.ContractCodeHistory, types.ContractCodeHistoryEntry{})
			if err := m.ContractCodeHistory[len(m.ContractCodeHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *KVModel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVModel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVModel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Models", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Models = append(m.Models, types.Model{})
			if err := m.Models[len(m.Models)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *CustomModel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustomModel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustomModel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = append(m.Msg[:0], dAtA[iNdEx:postIndex]...)
			if m.Msg == nil {
				m.Msg = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
