// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confio/twasm/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/CosmWasm/wasmd/x/wasm/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Wasm                        types.GenesisState `protobuf:"bytes,1,opt,name=wasm,proto3" json:"wasm_genesis,omitempty"`
	PrivilegedContractAddresses []string           `protobuf:"bytes,2,rep,name=privileged_contract_addresses,json=privilegedContractAddresses,proto3" json:"privileged_contract_addresses,omitempty"`
	PinnedContractAddresses     []string           `protobuf:"bytes,3,rep,name=pinned_contract_addresses,json=pinnedContractAddresses,proto3" json:"pinned_contract_addresses,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_89c4cd47eb0533ed, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetWasm() types.GenesisState {
	if m != nil {
		return m.Wasm
	}
	return types.GenesisState{}
}

func (m *GenesisState) GetPrivilegedContractAddresses() []string {
	if m != nil {
		return m.PrivilegedContractAddresses
	}
	return nil
}

func (m *GenesisState) GetPinnedContractAddresses() []string {
	if m != nil {
		return m.PinnedContractAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "confio.twasm.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("confio/twasm/v1beta1/genesis.proto", fileDescriptor_89c4cd47eb0533ed)
}

var fileDescriptor_89c4cd47eb0533ed = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x06, 0xe0, 0xa4, 0xbd, 0x5c, 0x30, 0xba, 0x0a, 0x45, 0x6b, 0xc5, 0x49, 0x69, 0xc1, 0x16,
	0x94, 0x19, 0xaa, 0x2f, 0xa0, 0x75, 0xe1, 0x5e, 0x17, 0x82, 0x9b, 0x32, 0x99, 0x1c, 0xe3, 0x80,
	0xc9, 0x09, 0x99, 0xb1, 0xda, 0xb7, 0xf0, 0x85, 0xdc, 0x77, 0xd9, 0xa5, 0xab, 0x20, 0xed, 0xae,
	0x4f, 0x21, 0x99, 0x24, 0x1a, 0xd0, 0xba, 0x0b, 0x39, 0xdf, 0xfc, 0xff, 0xc0, 0x19, 0xa7, 0x27,
	0x30, 0xbe, 0x97, 0xc8, 0xf4, 0x33, 0x57, 0x11, 0x9b, 0x8e, 0x7c, 0xd0, 0x7c, 0xc4, 0x42, 0x88,
	0x41, 0x49, 0x45, 0x93, 0x14, 0x35, 0xba, 0xad, 0xc2, 0x50, 0x63, 0x68, 0x69, 0x3a, 0xad, 0x10,
	0x43, 0x34, 0x80, 0xe5, 0x5f, 0x85, 0xed, 0x10, 0x81, 0x2a, 0x42, 0xc5, 0x7c, 0xae, 0xe0, 0x2b,
	0x4e, 0xa0, 0x8c, 0xcb, 0x79, 0x3f, 0x9f, 0x9b, 0xae, 0xcd, 0x85, 0xbd, 0xb7, 0x86, 0xb3, 0x73,
	0x55, 0xfc, 0xb9, 0xd1, 0x5c, 0x83, 0x7b, 0xeb, 0xfc, 0xcb, 0x79, 0xdb, 0xee, 0xda, 0xc3, 0xed,
	0xd3, 0x3e, 0xad, 0x42, 0x68, 0xfd, 0x46, 0xb4, 0x7e, 0x64, 0x4c, 0xe6, 0x99, 0x67, 0xad, 0x33,
	0x6f, 0x37, 0x27, 0x93, 0x32, 0xff, 0x04, 0x23, 0xa9, 0x21, 0x4a, 0xf4, 0xec, 0xda, 0x04, 0xba,
	0xe8, 0x1c, 0x26, 0xa9, 0x9c, 0xca, 0x47, 0x08, 0x21, 0x98, 0x08, 0x8c, 0x75, 0xca, 0x85, 0x9e,
	0xf0, 0x20, 0x48, 0x41, 0x29, 0x50, 0xed, 0x46, 0xb7, 0x39, 0xdc, 0x1a, 0x1f, 0xaf, 0x33, 0x6f,
	0xf0, 0x27, 0xac, 0x25, 0x1f, 0x7c, 0xc3, 0xcb, 0xd2, 0x5d, 0x54, 0xcc, 0x15, 0xce, 0x7e, 0x22,
	0xe3, 0xf8, 0xf7, 0xb2, 0xa6, 0x29, 0x1b, 0xac, 0x33, 0xaf, 0xbf, 0x11, 0xd5, 0x8a, 0xf6, 0x0a,
	0xf4, 0xa3, 0x64, 0x7c, 0x3e, 0x5f, 0x12, 0x7b, 0xb1, 0x24, 0xf6, 0xc7, 0x92, 0xd8, 0xaf, 0x2b,
	0x62, 0x2d, 0x56, 0xc4, 0x7a, 0x5f, 0x11, 0xeb, 0xee, 0x28, 0x94, 0xfa, 0xe1, 0xc9, 0xa7, 0x02,
	0x23, 0x56, 0x6d, 0x3e, 0x4c, 0x79, 0x00, 0xec, 0xa5, 0x7c, 0x02, 0x7a, 0x96, 0x80, 0xf2, 0xff,
	0x9b, 0x45, 0x9c, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x9d, 0xe8, 0x5f, 0x1f, 0x02, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PinnedContractAddresses) > 0 {
		for iNdEx := len(m.PinnedContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PinnedContractAddresses[iNdEx])
			copy(dAtA[i:], m.PinnedContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.PinnedContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PrivilegedContractAddresses) > 0 {
		for iNdEx := len(m.PrivilegedContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PrivilegedContractAddresses[iNdEx])
			copy(dAtA[i:], m.PrivilegedContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.PrivilegedContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Wasm.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Wasm.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PrivilegedContractAddresses) > 0 {
		for _, s := range m.PrivilegedContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PinnedContractAddresses) > 0 {
		for _, s := range m.PinnedContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wasm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Wasm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrivilegedContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrivilegedContractAddresses = append(m.PrivilegedContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PinnedContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PinnedContractAddresses = append(m.PinnedContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
