// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confio/twasm/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/CosmWasm/wasmd/x/wasm/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPrivilegedContractsResponse is the request type for the
// Query/PrivilegedContracts RPC method
type QueryPrivilegedContractsRequest struct {
}

func (m *QueryPrivilegedContractsRequest) Reset()         { *m = QueryPrivilegedContractsRequest{} }
func (m *QueryPrivilegedContractsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPrivilegedContractsRequest) ProtoMessage()    {}
func (*QueryPrivilegedContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dcfe179625ad95e, []int{0}
}
func (m *QueryPrivilegedContractsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPrivilegedContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPrivilegedContractsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPrivilegedContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPrivilegedContractsRequest.Merge(m, src)
}
func (m *QueryPrivilegedContractsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPrivilegedContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPrivilegedContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPrivilegedContractsRequest proto.InternalMessageInfo

// QueryPrivilegedContractsResponse is the response type for the
// Query/PrivilegedContracts RPC method
type QueryPrivilegedContractsResponse struct {
	// contracts are a set of contract addresses
	Contracts []string `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
}

func (m *QueryPrivilegedContractsResponse) Reset()         { *m = QueryPrivilegedContractsResponse{} }
func (m *QueryPrivilegedContractsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPrivilegedContractsResponse) ProtoMessage()    {}
func (*QueryPrivilegedContractsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dcfe179625ad95e, []int{1}
}
func (m *QueryPrivilegedContractsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPrivilegedContractsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPrivilegedContractsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPrivilegedContractsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPrivilegedContractsResponse.Merge(m, src)
}
func (m *QueryPrivilegedContractsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPrivilegedContractsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPrivilegedContractsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPrivilegedContractsResponse proto.InternalMessageInfo

func (m *QueryPrivilegedContractsResponse) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

// QueryContractsByCallbackTypeRequest is the request type for the
// Query/ContractsByCallbackType RPC method
type QueryContractsByCallbackTypeRequest struct {
	CallbackType string `protobuf:"bytes,2,opt,name=callback_type,json=callbackType,proto3" json:"callback_type,omitempty"`
}

func (m *QueryContractsByCallbackTypeRequest) Reset()         { *m = QueryContractsByCallbackTypeRequest{} }
func (m *QueryContractsByCallbackTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContractsByCallbackTypeRequest) ProtoMessage()    {}
func (*QueryContractsByCallbackTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dcfe179625ad95e, []int{2}
}
func (m *QueryContractsByCallbackTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractsByCallbackTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractsByCallbackTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractsByCallbackTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractsByCallbackTypeRequest.Merge(m, src)
}
func (m *QueryContractsByCallbackTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractsByCallbackTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractsByCallbackTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractsByCallbackTypeRequest proto.InternalMessageInfo

func (m *QueryContractsByCallbackTypeRequest) GetCallbackType() string {
	if m != nil {
		return m.CallbackType
	}
	return ""
}

// QueryContractsByCallbackTypeResponse is the response type for the
// Query/ContractsByCallbackType RPC method
type QueryContractsByCallbackTypeResponse struct {
	// contracts are a set of contract addresses
	Contracts []string `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
}

func (m *QueryContractsByCallbackTypeResponse) Reset()         { *m = QueryContractsByCallbackTypeResponse{} }
func (m *QueryContractsByCallbackTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContractsByCallbackTypeResponse) ProtoMessage()    {}
func (*QueryContractsByCallbackTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dcfe179625ad95e, []int{3}
}
func (m *QueryContractsByCallbackTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractsByCallbackTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractsByCallbackTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractsByCallbackTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractsByCallbackTypeResponse.Merge(m, src)
}
func (m *QueryContractsByCallbackTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractsByCallbackTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractsByCallbackTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractsByCallbackTypeResponse proto.InternalMessageInfo

func (m *QueryContractsByCallbackTypeResponse) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPrivilegedContractsRequest)(nil), "confio.twasm.v1beta1.QueryPrivilegedContractsRequest")
	proto.RegisterType((*QueryPrivilegedContractsResponse)(nil), "confio.twasm.v1beta1.QueryPrivilegedContractsResponse")
	proto.RegisterType((*QueryContractsByCallbackTypeRequest)(nil), "confio.twasm.v1beta1.QueryContractsByCallbackTypeRequest")
	proto.RegisterType((*QueryContractsByCallbackTypeResponse)(nil), "confio.twasm.v1beta1.QueryContractsByCallbackTypeResponse")
}

func init() { proto.RegisterFile("confio/twasm/v1beta1/query.proto", fileDescriptor_1dcfe179625ad95e) }

var fileDescriptor_1dcfe179625ad95e = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xce, 0xcf, 0x4b,
	0xcb, 0xcc, 0xd7, 0x2f, 0x29, 0x4f, 0x2c, 0xce, 0xd5, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34,
	0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x81, 0xa8,
	0xd0, 0x03, 0xab, 0xd0, 0x83, 0xaa, 0x90, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd0, 0x07,
	0xb1, 0x20, 0x6a, 0xa5, 0x14, 0x93, 0xf3, 0x8b, 0x73, 0xc1, 0x26, 0xa1, 0x18, 0x57, 0x52, 0x59,
	0x90, 0x5a, 0x0c, 0x55, 0x22, 0x93, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9,
	0x9f, 0x98, 0x97, 0x97, 0x5f, 0x92, 0x58, 0x92, 0x99, 0x9f, 0x07, 0x93, 0xd5, 0x02, 0x19, 0x90,
	0x5f, 0xac, 0x9f, 0x94, 0x58, 0x9c, 0x0a, 0x71, 0x05, 0xdc, 0x90, 0x82, 0xc4, 0xf4, 0xcc, 0x3c,
	0xb0, 0x62, 0x88, 0x5a, 0x25, 0x45, 0x2e, 0xf9, 0x40, 0x90, 0x8a, 0x80, 0xa2, 0xcc, 0xb2, 0xcc,
	0x9c, 0xd4, 0xf4, 0xd4, 0x14, 0xe7, 0xfc, 0xbc, 0x92, 0xa2, 0xc4, 0xe4, 0x92, 0xe2, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x07, 0x2e, 0x05, 0xdc, 0x4a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x64, 0xb8, 0x38, 0x93, 0x61, 0x82, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x08,
	0x01, 0x25, 0x2f, 0x2e, 0x65, 0xb0, 0x09, 0x70, 0x7d, 0x4e, 0x95, 0xce, 0x89, 0x39, 0x39, 0x49,
	0x89, 0xc9, 0xd9, 0x21, 0x95, 0x05, 0xa9, 0x50, 0x8b, 0x84, 0x94, 0xb9, 0x78, 0x93, 0xa1, 0xc2,
	0xf1, 0x20, 0xdf, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xf1, 0x24, 0x23, 0xa9, 0x55, 0x72,
	0xe1, 0x52, 0xc1, 0x6f, 0x16, 0x31, 0x2e, 0x32, 0xea, 0x64, 0xe6, 0x62, 0x05, 0x1b, 0x23, 0xb4,
	0x91, 0x91, 0x4b, 0x18, 0x8b, 0xcf, 0x84, 0x4c, 0xf5, 0xb0, 0x45, 0x99, 0x1e, 0x81, 0xc0, 0x92,
	0x32, 0x23, 0x55, 0x1b, 0xc4, 0xb9, 0x4a, 0xda, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x52, 0x15, 0x52,
	0x46, 0x4b, 0x44, 0x70, 0x27, 0xeb, 0x17, 0xc0, 0x75, 0x0b, 0x9d, 0x66, 0xe4, 0x12, 0xc7, 0xe1,
	0x7f, 0x21, 0x4b, 0x3c, 0x0e, 0xc0, 0x1f, 0xfe, 0x52, 0x56, 0xe4, 0x68, 0x85, 0xba, 0xdf, 0x12,
	0xec, 0x7e, 0x63, 0x21, 0x43, 0x9c, 0xee, 0x87, 0xc5, 0xa2, 0x7e, 0x35, 0x4a, 0x24, 0xd7, 0x3a,
	0x39, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e,
	0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x5a, 0x7a, 0x66, 0x49,
	0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x2c, 0x8b, 0xa5, 0x17, 0x25, 0xa6, 0xa4, 0xea,
	0x57, 0x40, 0xad, 0x01, 0x67, 0x8a, 0x24, 0x36, 0x70, 0x5a, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x97, 0x66, 0x50, 0x88, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// PrivilegedContracts returns all privileged contracts
	PrivilegedContracts(ctx context.Context, in *QueryPrivilegedContractsRequest, opts ...grpc.CallOption) (*QueryPrivilegedContractsResponse, error)
	// ContractsByCallbackType returns all contracts that have registered for the
	// callback type
	ContractsByCallbackType(ctx context.Context, in *QueryContractsByCallbackTypeRequest, opts ...grpc.CallOption) (*QueryContractsByCallbackTypeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PrivilegedContracts(ctx context.Context, in *QueryPrivilegedContractsRequest, opts ...grpc.CallOption) (*QueryPrivilegedContractsResponse, error) {
	out := new(QueryPrivilegedContractsResponse)
	err := c.cc.Invoke(ctx, "/confio.twasm.v1beta1.Query/PrivilegedContracts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ContractsByCallbackType(ctx context.Context, in *QueryContractsByCallbackTypeRequest, opts ...grpc.CallOption) (*QueryContractsByCallbackTypeResponse, error) {
	out := new(QueryContractsByCallbackTypeResponse)
	err := c.cc.Invoke(ctx, "/confio.twasm.v1beta1.Query/ContractsByCallbackType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// PrivilegedContracts returns all privileged contracts
	PrivilegedContracts(context.Context, *QueryPrivilegedContractsRequest) (*QueryPrivilegedContractsResponse, error)
	// ContractsByCallbackType returns all contracts that have registered for the
	// callback type
	ContractsByCallbackType(context.Context, *QueryContractsByCallbackTypeRequest) (*QueryContractsByCallbackTypeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PrivilegedContracts(ctx context.Context, req *QueryPrivilegedContractsRequest) (*QueryPrivilegedContractsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivilegedContracts not implemented")
}
func (*UnimplementedQueryServer) ContractsByCallbackType(ctx context.Context, req *QueryContractsByCallbackTypeRequest) (*QueryContractsByCallbackTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractsByCallbackType not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PrivilegedContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPrivilegedContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PrivilegedContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/confio.twasm.v1beta1.Query/PrivilegedContracts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PrivilegedContracts(ctx, req.(*QueryPrivilegedContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ContractsByCallbackType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryContractsByCallbackTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractsByCallbackType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/confio.twasm.v1beta1.Query/ContractsByCallbackType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractsByCallbackType(ctx, req.(*QueryContractsByCallbackTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "confio.twasm.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrivilegedContracts",
			Handler:    _Query_PrivilegedContracts_Handler,
		},
		{
			MethodName: "ContractsByCallbackType",
			Handler:    _Query_ContractsByCallbackType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "confio/twasm/v1beta1/query.proto",
}

func (m *QueryPrivilegedContractsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPrivilegedContractsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPrivilegedContractsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPrivilegedContractsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPrivilegedContractsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPrivilegedContractsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Contracts[iNdEx])
			copy(dAtA[i:], m.Contracts[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Contracts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractsByCallbackTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractsByCallbackTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractsByCallbackTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallbackType) > 0 {
		i -= len(m.CallbackType)
		copy(dAtA[i:], m.CallbackType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CallbackType)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractsByCallbackTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractsByCallbackTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractsByCallbackTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Contracts[iNdEx])
			copy(dAtA[i:], m.Contracts[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Contracts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPrivilegedContractsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPrivilegedContractsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Contracts) > 0 {
		for _, s := range m.Contracts {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryContractsByCallbackTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CallbackType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContractsByCallbackTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Contracts) > 0 {
		for _, s := range m.Contracts {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPrivilegedContractsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPrivilegedContractsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPrivilegedContractsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPrivilegedContractsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPrivilegedContractsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPrivilegedContractsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractsByCallbackTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractsByCallbackTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractsByCallbackTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractsByCallbackTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractsByCallbackTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractsByCallbackTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
