// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confio/poe/v1beta1/poe.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "github.com/tendermint/tendermint/proto/tendermint/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PoEContractType type of PoE contract
type PoEContractType int32

const (
	PoEContractTypeUndefined          PoEContractType = 0
	PoEContractTypeStaking            PoEContractType = 1
	PoEContractTypeValset             PoEContractType = 2
	PoEContractTypeEngagement         PoEContractType = 3
	PoEContractTypeMixer              PoEContractType = 4
	PoEContractTypeDistribution       PoEContractType = 5
	PoEContractTypeOversightCommittee PoEContractType = 6
)

var PoEContractType_name = map[int32]string{
	0: "UNDEFINED",
	1: "STAKING",
	2: "VALSET",
	3: "ENGAGEMENT",
	4: "MIXER",
	5: "DISTRIBUTION",
	6: "TRUSTED_CIRCLE",
}

var PoEContractType_value = map[string]int32{
	"UNDEFINED":      0,
	"STAKING":        1,
	"VALSET":         2,
	"ENGAGEMENT":     3,
	"MIXER":          4,
	"DISTRIBUTION":   5,
	"TRUSTED_CIRCLE": 6,
}

func (x PoEContractType) String() string {
	return proto.EnumName(PoEContractType_name, int32(x))
}

func (PoEContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df6d9ea68813554a, []int{0}
}

// Params defines the parameters for the PoE module.
type Params struct {
	// HistoricalEntries is the number of historical entries to persist.
	HistoricalEntries uint32 `protobuf:"varint,1,opt,name=historical_entries,json=historicalEntries,proto3" json:"historical_entries,omitempty" yaml:"historical_entries"`
	// InitialValEngagementPoints defines the number of engagement for any new
	// validator joining post genesis
	InitialValEngagementPoints uint64 `protobuf:"varint,2,opt,name=initial_val_engagement_points,json=initialValEngagementPoints,proto3" json:"initial_val_engagement_points,omitempty" yaml:"initial_val_engagement_points"`
	// MinDelegationAmount defines the minimum amount a post genesis validator
	// needs to self delegate to receive any engagement points. One must be
	// exceeded. No minimum condition set when empty.
	MinDelegationAmounts github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=min_delegation_amounts,json=minDelegationAmounts,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"min_delegation_amounts" yaml:"min_delegation_amounts"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6d9ea68813554a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetHistoricalEntries() uint32 {
	if m != nil {
		return m.HistoricalEntries
	}
	return 0
}

func (m *Params) GetInitialValEngagementPoints() uint64 {
	if m != nil {
		return m.InitialValEngagementPoints
	}
	return 0
}

func (m *Params) GetMinDelegationAmounts() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MinDelegationAmounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("confio.poe.v1beta1.PoEContractType", PoEContractType_name, PoEContractType_value)
	proto.RegisterType((*Params)(nil), "confio.poe.v1beta1.Params")
}

func init() { proto.RegisterFile("confio/poe/v1beta1/poe.proto", fileDescriptor_df6d9ea68813554a) }

var fileDescriptor_df6d9ea68813554a = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcd, 0x6e, 0xd3, 0x4a,
	0x18, 0x86, 0xe3, 0xb4, 0xcd, 0x39, 0x67, 0x0e, 0x3f, 0xc1, 0x2a, 0x55, 0x62, 0x12, 0xdb, 0x0a,
	0x45, 0x44, 0xa0, 0xc6, 0x2a, 0xb0, 0xea, 0x02, 0x29, 0x3f, 0xa6, 0x8a, 0x68, 0x43, 0x49, 0x9c,
	0x0a, 0xb1, 0xb1, 0x26, 0xf6, 0xd4, 0x1d, 0xd5, 0x9e, 0x89, 0x3c, 0x93, 0xaa, 0xb9, 0x03, 0xe4,
	0x15, 0x4b, 0x36, 0x96, 0x2a, 0xd8, 0x71, 0x25, 0x5d, 0x96, 0x1d, 0xab, 0x80, 0xda, 0x0d, 0xeb,
	0x5c, 0x01, 0xf2, 0x4f, 0x5a, 0x61, 0x10, 0x9b, 0x64, 0xbe, 0x79, 0x1f, 0xbf, 0xdf, 0xe8, 0xfd,
	0xec, 0x01, 0x15, 0x8b, 0x92, 0x03, 0x4c, 0xb5, 0x31, 0x45, 0xda, 0xf1, 0xe6, 0x08, 0x71, 0xb8,
	0x19, 0xad, 0x1b, 0x63, 0x9f, 0x72, 0x2a, 0x8a, 0x89, 0xda, 0x88, 0x76, 0x52, 0x55, 0x5a, 0x75,
	0xa8, 0x43, 0x63, 0x59, 0x8b, 0x56, 0x09, 0x29, 0x95, 0x1d, 0x4a, 0x1d, 0x17, 0x69, 0x71, 0x35,
	0x9a, 0x1c, 0x68, 0x90, 0x4c, 0x53, 0x49, 0xce, 0x4a, 0xf6, 0xc4, 0x87, 0x1c, 0x53, 0x92, 0xea,
	0x4a, 0x56, 0xe7, 0xd8, 0x43, 0x8c, 0x43, 0x6f, 0xbc, 0xf0, 0xb6, 0x28, 0xf3, 0x28, 0x33, 0x93,
	0xa6, 0x49, 0xb1, 0xf0, 0x4e, 0x2a, 0x6d, 0x04, 0xd9, 0xf5, 0xf9, 0x2d, 0x8a, 0x17, 0xde, 0xeb,
	0xa9, 0xce, 0x38, 0x3c, 0xc2, 0xc4, 0xb9, 0x42, 0xd2, 0x3a, 0xa5, 0x2a, 0x1c, 0x11, 0x1b, 0xf9,
	0x1e, 0x26, 0x5c, 0xe3, 0xd3, 0x31, 0x62, 0xc9, 0x6f, 0xa2, 0xd6, 0xe6, 0x79, 0x50, 0xd8, 0x83,
	0x3e, 0xf4, 0x98, 0xb8, 0x03, 0xc4, 0x43, 0xcc, 0x38, 0xf5, 0xb1, 0x05, 0x5d, 0x13, 0x11, 0xee,
	0x63, 0xc4, 0x4a, 0x82, 0x2a, 0xd4, 0x6f, 0xb6, 0xaa, 0xf3, 0x99, 0x52, 0x9e, 0x42, 0xcf, 0xdd,
	0xaa, 0xfd, 0xce, 0xd4, 0xfa, 0x77, 0xae, 0x37, 0xf5, 0x64, 0x4f, 0x3c, 0x02, 0x55, 0x4c, 0x30,
	0xc7, 0xd0, 0x35, 0x8f, 0x63, 0xd4, 0x81, 0x0e, 0xf2, 0x10, 0xe1, 0xe6, 0x98, 0x62, 0xc2, 0x59,
	0x29, 0xaf, 0x0a, 0xf5, 0xe5, 0x56, 0x7d, 0x3e, 0x53, 0xd6, 0x13, 0xe3, 0xbf, 0xe2, 0xb5, 0xbe,
	0x94, 0xea, 0xfb, 0x51, 0x8f, 0x85, 0xba, 0x17, 0x8b, 0xe2, 0x47, 0x01, 0xac, 0x79, 0x98, 0x98,
	0x36, 0x72, 0x91, 0x13, 0xc7, 0x6f, 0x42, 0x8f, 0x4e, 0xa2, 0x36, 0x4b, 0xea, 0x52, 0xfd, 0xff,
	0x27, 0xe5, 0x46, 0x9a, 0x6c, 0x94, 0xe5, 0x62, 0xda, 0x8d, 0x36, 0xc5, 0xa4, 0xf5, 0xfa, 0x6c,
	0xa6, 0xe4, 0xe6, 0x33, 0xa5, 0x9a, 0x9c, 0xe2, 0xcf, 0x36, 0xb5, 0xcf, 0xdf, 0x94, 0xba, 0x83,
	0xf9, 0xe1, 0x64, 0xd4, 0xb0, 0xa8, 0x97, 0xce, 0x29, 0xfd, 0xdb, 0x60, 0xf6, 0x51, 0x1a, 0x6a,
	0xe4, 0xc8, 0xfa, 0xab, 0x1e, 0x26, 0x9d, 0x2b, 0x8f, 0x66, 0x62, 0xb1, 0xf5, 0xef, 0x87, 0x53,
	0x25, 0xf7, 0xe3, 0x54, 0x11, 0x1e, 0x7d, 0xc9, 0x83, 0xdb, 0x7b, 0x54, 0x6f, 0x53, 0xc2, 0x7d,
	0x68, 0x71, 0x63, 0x3a, 0x46, 0xe2, 0x63, 0xf0, 0xdf, 0xb0, 0xd7, 0xd1, 0x5f, 0x74, 0x7b, 0x7a,
	0xa7, 0x98, 0x93, 0x2a, 0x41, 0xa8, 0x96, 0x32, 0xcc, 0x90, 0xd8, 0xe8, 0x00, 0x13, 0x64, 0x8b,
	0x0f, 0xc1, 0x3f, 0x03, 0xa3, 0xf9, 0xb2, 0xdb, 0xdb, 0x2e, 0x0a, 0x92, 0x14, 0x84, 0xea, 0x5a,
	0x06, 0x1d, 0x24, 0xaf, 0x80, 0xf8, 0x00, 0x14, 0xf6, 0x9b, 0x3b, 0x03, 0xdd, 0x28, 0xe6, 0xa5,
	0x72, 0x10, 0xaa, 0x77, 0x33, 0xdc, 0x3e, 0x74, 0x19, 0xe2, 0xe2, 0x06, 0x00, 0x7a, 0x6f, 0xbb,
	0xb9, 0xad, 0xef, 0xea, 0x3d, 0xa3, 0xb8, 0x24, 0x55, 0x83, 0x50, 0x2d, 0x67, 0xd0, 0xeb, 0xd0,
	0xc5, 0xfb, 0x60, 0x65, 0xb7, 0xfb, 0x46, 0xef, 0x17, 0x97, 0xa5, 0x52, 0x10, 0xaa, 0xab, 0x19,
	0x72, 0x17, 0x9f, 0x20, 0x5f, 0xdc, 0x04, 0x37, 0x3a, 0xdd, 0x81, 0xd1, 0xef, 0xb6, 0x86, 0x46,
	0xf7, 0x55, 0xaf, 0xb8, 0x22, 0x29, 0x41, 0xa8, 0xde, 0xcb, 0xb0, 0x1d, 0xcc, 0xb8, 0x8f, 0x47,
	0x93, 0x28, 0x28, 0xf1, 0x19, 0xb8, 0x65, 0xf4, 0x87, 0x03, 0x43, 0xef, 0x98, 0xed, 0x6e, 0xbf,
	0xbd, 0xa3, 0x17, 0x0b, 0x92, 0x1a, 0x84, 0x6a, 0x25, 0xf3, 0x90, 0xe1, 0x4f, 0x18, 0x47, 0x76,
	0x1b, 0xfb, 0x96, 0x8b, 0xa4, 0xe5, 0x77, 0x9f, 0xe4, 0x5c, 0xeb, 0xf9, 0xd9, 0x85, 0x2c, 0x9c,
	0x5f, 0xc8, 0xc2, 0xf7, 0x0b, 0x59, 0x78, 0x7f, 0x29, 0xe7, 0xce, 0x2f, 0xe5, 0xdc, 0xd7, 0x4b,
	0x39, 0xf7, 0x76, 0xfd, 0x97, 0xb9, 0xc5, 0x17, 0x02, 0x77, 0x7c, 0x68, 0x23, 0xed, 0x24, 0xbe,
	0x19, 0xe2, 0xc9, 0x8d, 0x0a, 0xf1, 0xf7, 0xf0, 0xf4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7,
	0x0d, 0x74, 0xfc, 0x34, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.HistoricalEntries != that1.HistoricalEntries {
		return false
	}
	if this.InitialValEngagementPoints != that1.InitialValEngagementPoints {
		return false
	}
	if len(this.MinDelegationAmounts) != len(that1.MinDelegationAmounts) {
		return false
	}
	for i := range this.MinDelegationAmounts {
		if !this.MinDelegationAmounts[i].Equal(&that1.MinDelegationAmounts[i]) {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinDelegationAmounts) > 0 {
		for iNdEx := len(m.MinDelegationAmounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinDelegationAmounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoe(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.InitialValEngagementPoints != 0 {
		i = encodeVarintPoe(dAtA, i, uint64(m.InitialValEngagementPoints))
		i--
		dAtA[i] = 0x10
	}
	if m.HistoricalEntries != 0 {
		i = encodeVarintPoe(dAtA, i, uint64(m.HistoricalEntries))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoe(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoe(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HistoricalEntries != 0 {
		n += 1 + sovPoe(uint64(m.HistoricalEntries))
	}
	if m.InitialValEngagementPoints != 0 {
		n += 1 + sovPoe(uint64(m.InitialValEngagementPoints))
	}
	if len(m.MinDelegationAmounts) > 0 {
		for _, e := range m.MinDelegationAmounts {
			l = e.Size()
			n += 1 + l + sovPoe(uint64(l))
		}
	}
	return n
}

func sovPoe(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoe(x uint64) (n int) {
	return sovPoe(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoe
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalEntries", wireType)
			}
			m.HistoricalEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HistoricalEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialValEngagementPoints", wireType)
			}
			m.InitialValEngagementPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialValEngagementPoints |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDelegationAmounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoe
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoe
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoe
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinDelegationAmounts = append(m.MinDelegationAmounts, types.Coin{})
			if err := m.MinDelegationAmounts[len(m.MinDelegationAmounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoe(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoe
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoe(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoe
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoe
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoe
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoe
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoe
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoe
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoe        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoe          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoe = fmt.Errorf("proto: unexpected end of group")
)
